# Site settings
title: Drew Brinkley
author:
  name: Drew Brinkley
  email: drewbrinkley24@gmail.com
description: "Drew Brinkley's personal website on GH-pages."

# Build settings
remote_theme: jekyll/minima

# generate social links in footer
social_links:
  linkedin: drew-brinkley-25a682149
  github: drewbrinkley
